/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package akademikjurusan;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Reza
 */
public class FView extends javax.swing.JFrame {

    /**
     * Creates new form FView
     */
    public FView() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopView = new javax.swing.JDesktopPane();
        layerCari = new javax.swing.JLayeredPane();
        lblNIM = new javax.swing.JLabel();
        txtNIM = new javax.swing.JTextField();
        bCari = new javax.swing.JButton();
        lblSemester = new javax.swing.JLabel();
        txtSemester = new javax.swing.JTextField();
        layerView = new javax.swing.JLayeredPane();
        TotalSKS = new javax.swing.JLabel();
        TotalSKSxNilai = new javax.swing.JLabel();
        IP = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        desktopView.setBackground(new java.awt.Color(255, 255, 255));

        layerCari.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cari Mahasiswa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        lblNIM.setText("NIM");
        layerCari.add(lblNIM);
        lblNIM.setBounds(10, 20, 50, 14);
        layerCari.add(txtNIM);
        txtNIM.setBounds(90, 20, 160, 20);

        bCari.setText("Cari");
        bCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCariActionPerformed(evt);
            }
        });
        layerCari.add(bCari);
        bCari.setBounds(410, 20, 100, 23);

        lblSemester.setText("Semester");
        layerCari.add(lblSemester);
        lblSemester.setBounds(260, 20, 70, 14);
        layerCari.add(txtSemester);
        txtSemester.setBounds(340, 20, 40, 20);

        desktopView.add(layerCari);
        layerCari.setBounds(10, 10, 530, 60);

        layerView.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "View KHS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        layerView.add(TotalSKS);
        TotalSKS.setBounds(260, 360, 60, 20);
        layerView.add(TotalSKSxNilai);
        TotalSKSxNilai.setBounds(480, 360, 60, 20);
        layerView.add(IP);
        IP.setBounds(660, 360, 100, 20);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "NIM", "Matkul", "Semester", "Nilai Tugas", "Nilai UTS", "Nilai UAS"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        layerView.add(jScrollPane3);
        jScrollPane3.setBounds(20, 20, 560, 200);

        desktopView.add(layerView);
        layerView.setBounds(10, 80, 600, 240);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopView, javax.swing.GroupLayout.DEFAULT_SIZE, 621, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(desktopView, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCariActionPerformed
        // TODO add your handling code here:
        try {
            Connection conn = Koneksi.getKoneksi();

            String sql="SELECT * FROM penilaian WHERE nim=?";
            PreparedStatement st=conn.prepareStatement(sql);
            st.setString(1,txtNIM.getText());
            ResultSet rs= st.executeQuery();

            String sql2="SELECT * FROM penilaian WHERE nim=? and semester=?";
            PreparedStatement st2=conn.prepareStatement(sql2);
            st2.setString(1,txtNIM.getText());
            st2.setString(2,txtSemester.getText());
            ResultSet rs2= st2.executeQuery();

            if( rs.next() && rs2.next()){
                String nim = rs.getString("nim");
                String kode_mk = rs.getString("kode_mk");
                String semester = rs.getString("semester");
                String nilai_tugas = rs.getString("nilai_tugas");
                String nilai_uts = rs.getString("nilai_uts");
                String nilai_uas = rs.getString("nilai_uas");
                int i = 0;
                
                jTable3.getModel().setValueAt(nim, i, 0);
                jTable3.getModel().setValueAt(kode_mk, i, 1);
                jTable3.getModel().setValueAt(semester, i, 2);
                jTable3.getModel().setValueAt(nilai_tugas, i, 3);
                jTable3.getModel().setValueAt(nilai_uts, i, 4);
                jTable3.getModel().setValueAt(nilai_uas, i, 5);
                
            } else{
                JOptionPane.showMessageDialog(this, "NIM Tidak Ada","Informasi",JOptionPane.INFORMATION_MESSAGE);
                
            }
        } // akhir try
        catch(Exception e){
            System.out.println("Koneksi Gagal " +e.getMessage());
        }
    }//GEN-LAST:event_bCariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FView().setVisible(true);
            }
        });
    }
    
    public static void tampilPenilaian(){
        final String JDBC_DRIVER = "com.mysql.jdbc.Driver";  
        final String DB_URL = "jdbc:mysql://localhost/dbakademik";

        //  Database credentials
        final String USER = "root";
        final String PASS = "";
   
        Connection conn = null;
        Statement stmt = null;
        try{
           //STEP 2: Register JDBC driver
           Class.forName("com.mysql.jdbc.Driver");

           //STEP 3: Open a connection
           System.out.println("Connecting to a selected database...");
           conn = DriverManager.getConnection(DB_URL, USER, PASS);
           System.out.println("Connected database successfully...");
                System.out.println("Creating statement...");
             stmt = conn.createStatement();

             String sql = "SELECT * FROM penilaian WHERE 1 LIMIT 0, 10";
             ResultSet rs = stmt.executeQuery(sql);
             //STEP 5: Extract data from result set
             int i=0;
        
             while(rs.next()){
                //Retrieve by column name
                String nim  = rs.getString("nim");
                String kode_mk = rs.getString("kode_mk");
                String semester = rs.getString("semester");
                String nilai_tugas = rs.getString("nilai_tugas");
                String nilai_uts = rs.getString("nilai_uts");
                String nilai_uas = rs.getString("nilai_uas");


            
                jTable3.getModel().setValueAt(nim, i, 0);
                jTable3.getModel().setValueAt(kode_mk, i, 1);
                jTable3.getModel().setValueAt(semester, i, 2);
                jTable3.getModel().setValueAt(nilai_tugas, i, 3);
                jTable3.getModel().setValueAt(nilai_uts, i, 4);
                jTable3.getModel().setValueAt(nilai_uas, i, 5);
                
                i++;
             }
             rs.close();
          }catch(SQLException se){
             //Handle errors for JDBC
             se.printStackTrace();
          }catch(Exception e){
             //Handle errors for Class.forName
             e.printStackTrace();
          }finally{
             //finally block used to close resources
             try{
                if(stmt!=null)
                   conn.close();
             }catch(SQLException se){
             }// do nothing
             try{
                if(conn!=null)
                   conn.close();
             }catch(SQLException se){
                se.printStackTrace();
             }//end finally try
          }//end try
          System.out.println("Goodbye!");
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IP;
    private javax.swing.JLabel TotalSKS;
    private javax.swing.JLabel TotalSKSxNilai;
    private javax.swing.JButton bCari;
    private javax.swing.JDesktopPane desktopView;
    private javax.swing.JScrollPane jScrollPane3;
    private static javax.swing.JTable jTable3;
    private javax.swing.JLayeredPane layerCari;
    private javax.swing.JLayeredPane layerView;
    private javax.swing.JLabel lblNIM;
    private javax.swing.JLabel lblSemester;
    private javax.swing.JTextField txtNIM;
    private javax.swing.JTextField txtSemester;
    // End of variables declaration//GEN-END:variables
}
