/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package akademikjurusan;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
/**
 *
 * @author Reza
 */
public class InputForm extends javax.swing.JFrame {

    /**
     * Creates new form InputForm
     */
    public InputForm() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        layerMataKuliah = new javax.swing.JLayeredPane();
        pMataKuliah = new javax.swing.JPanel();
        lblKodeMataKuliah = new javax.swing.JLabel();
        txtKodeMataKuliah = new javax.swing.JTextField();
        lblSKS = new javax.swing.JLabel();
        txtSKS = new javax.swing.JTextField();
        txtNamaMataKuliah = new javax.swing.JTextField();
        lblNamaMataKuliah = new javax.swing.JLabel();
        layerDosen = new javax.swing.JLayeredPane();
        pDosen = new javax.swing.JPanel();
        lblNIP = new javax.swing.JLabel();
        lblNamaDosen = new javax.swing.JLabel();
        txtNamaDosen = new javax.swing.JTextField();
        txtNIP = new javax.swing.JTextField();
        layerMahasiswa = new javax.swing.JLayeredPane();
        pMahasiswa = new javax.swing.JPanel();
        lblNIM = new javax.swing.JLabel();
        lblNamaMahasiswa = new javax.swing.JLabel();
        lblKelas = new javax.swing.JLabel();
        txtNIM = new javax.swing.JTextField();
        txtNamaMahasiswa = new javax.swing.JTextField();
        txtKelas = new javax.swing.JTextField();
        lblFakultas = new javax.swing.JLabel();
        lblProdi = new javax.swing.JLabel();
        txtFakultas = new javax.swing.JTextField();
        txtProdi = new javax.swing.JTextField();
        bTambah = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        layerMataKuliah.setBorder(javax.swing.BorderFactory.createTitledBorder("Mata Kuliah"));

        pMataKuliah.setBackground(new java.awt.Color(102, 102, 102));

        lblKodeMataKuliah.setText("Kode Mata Kuliah");

        txtKodeMataKuliah.setEnabled(false);
        txtKodeMataKuliah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKodeMataKuliahActionPerformed(evt);
            }
        });
        txtKodeMataKuliah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtKodeMataKuliahKeyPressed(evt);
            }
        });

        lblSKS.setText("SKS");

        lblNamaMataKuliah.setText("Nama Mata Kuliah");

        javax.swing.GroupLayout pMataKuliahLayout = new javax.swing.GroupLayout(pMataKuliah);
        pMataKuliah.setLayout(pMataKuliahLayout);
        pMataKuliahLayout.setHorizontalGroup(
            pMataKuliahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMataKuliahLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pMataKuliahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNamaMataKuliah)
                    .addComponent(lblKodeMataKuliah))
                .addGap(18, 18, 18)
                .addGroup(pMataKuliahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pMataKuliahLayout.createSequentialGroup()
                        .addComponent(txtKodeMataKuliah, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblSKS)
                        .addGap(18, 18, 18)
                        .addComponent(txtSKS, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE))
                    .addComponent(txtNamaMataKuliah))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        pMataKuliahLayout.setVerticalGroup(
            pMataKuliahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMataKuliahLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pMataKuliahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKodeMataKuliah)
                    .addComponent(txtKodeMataKuliah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSKS)
                    .addComponent(txtSKS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pMataKuliahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNamaMataKuliah)
                    .addComponent(txtNamaMataKuliah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        layerMataKuliah.add(pMataKuliah);
        pMataKuliah.setBounds(10, 20, 380, 80);

        layerDosen.setBorder(javax.swing.BorderFactory.createTitledBorder("Dosen Wali"));

        pDosen.setBackground(new java.awt.Color(0, 0, 0));

        lblNIP.setForeground(new java.awt.Color(204, 204, 204));
        lblNIP.setText("NIP");

        lblNamaDosen.setForeground(new java.awt.Color(204, 204, 204));
        lblNamaDosen.setText("Nama Dosen");

        txtNamaDosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaDosenActionPerformed(evt);
            }
        });

        txtNIP.setEnabled(false);
        txtNIP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNIPKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout pDosenLayout = new javax.swing.GroupLayout(pDosen);
        pDosen.setLayout(pDosenLayout);
        pDosenLayout.setHorizontalGroup(
            pDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDosenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNamaDosen)
                    .addComponent(lblNIP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNamaDosen)
                    .addComponent(txtNIP, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE))
                .addGap(32, 32, 32))
        );
        pDosenLayout.setVerticalGroup(
            pDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDosenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNIP)
                    .addComponent(txtNIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNamaDosen)
                    .addComponent(txtNamaDosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layerDosen.add(pDosen);
        pDosen.setBounds(20, 20, 280, 80);

        layerMahasiswa.setBorder(javax.swing.BorderFactory.createTitledBorder("Mahasiswa"));

        pMahasiswa.setBackground(new java.awt.Color(0, 0, 0));
        pMahasiswa.setForeground(new java.awt.Color(204, 204, 204));

        lblNIM.setForeground(new java.awt.Color(204, 204, 204));
        lblNIM.setText("NIM");

        lblNamaMahasiswa.setForeground(new java.awt.Color(204, 204, 204));
        lblNamaMahasiswa.setText("Nama Mahasiswa");

        lblKelas.setForeground(new java.awt.Color(204, 204, 204));
        lblKelas.setText("T.A");

        txtNIM.setEnabled(false);
        txtNIM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNIMActionPerformed(evt);
            }
        });
        txtNIM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNIMKeyPressed(evt);
            }
        });

        lblFakultas.setForeground(new java.awt.Color(204, 204, 204));
        lblFakultas.setText("Jurusan");

        lblProdi.setForeground(new java.awt.Color(204, 204, 204));
        lblProdi.setText("Jenis Kelamin");

        javax.swing.GroupLayout pMahasiswaLayout = new javax.swing.GroupLayout(pMahasiswa);
        pMahasiswa.setLayout(pMahasiswaLayout);
        pMahasiswaLayout.setHorizontalGroup(
            pMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMahasiswaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNamaMahasiswa)
                    .addComponent(lblNIM)
                    .addComponent(lblKelas))
                .addGap(32, 32, 32)
                .addGroup(pMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNIM, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNamaMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(pMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFakultas)
                    .addComponent(lblProdi))
                .addGap(32, 32, 32)
                .addGroup(pMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtProdi)
                    .addComponent(txtFakultas, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE))
                .addGap(33, 33, 33))
        );
        pMahasiswaLayout.setVerticalGroup(
            pMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMahasiswaLayout.createSequentialGroup()
                .addGroup(pMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pMahasiswaLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(pMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNIM)
                            .addComponent(txtNIM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNamaMahasiswa)
                            .addComponent(txtNamaMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblKelas)
                            .addComponent(txtKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pMahasiswaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFakultas)
                            .addComponent(txtFakultas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(pMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblProdi)
                            .addComponent(txtProdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        layerMahasiswa.add(pMahasiswa);
        pMahasiswa.setBounds(10, 20, 710, 110);

        bTambah.setText("Tambah");
        bTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTambahActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Sitka Text", 0, 13)); // NOI18N
        jLabel1.setText("Semester");

        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "NIM", "Matkul", "Semester", "Nilai Tugas", "Nilai UTS", "Nilai UAS"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jLabel3.setFont(new java.awt.Font("Sitka Text", 0, 13)); // NOI18N
        jLabel3.setText("Nilai Tugas");

        jLabel4.setFont(new java.awt.Font("Sitka Text", 0, 13)); // NOI18N
        jLabel4.setText("Nilai UTS");

        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Sitka Text", 0, 13)); // NOI18N
        jLabel6.setText("Nilai UAS");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jButton5.setText("Refresh");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(layerMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(layerMataKuliah, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(layerDosen, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(layerMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(layerDosen, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(layerMataKuliah, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton5)
                    .addComponent(jButton4)
                    .addComponent(bTambah))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layerDosen.getAccessibleContext().setAccessibleName("Dosen");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtKodeMataKuliahKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKodeMataKuliahKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==10){
            try {
                Connection conn = Koneksi.getKoneksi();

                String sql="SELECT * FROM matakuliah WHERE kode_mk=?";
                PreparedStatement st=conn.prepareStatement(sql);
                st.setString(1,txtKodeMataKuliah.getText());
                ResultSet rs= st.executeQuery();
                if( rs.next()){
                    String nama_mk = rs.getString("nama_mk");
                    String sks = rs.getString("sks");
                    txtNamaMataKuliah.setText(nama_mk);
                    txtSKS.setText(sks);
                } else{
                    JOptionPane.showMessageDialog(this, "Kode Mata Kuliah Tidak  Ada","Informasi",JOptionPane.INFORMATION_MESSAGE);
                    txtNamaMataKuliah.setText("");
                    txtSKS.setText("");
                }
            } // akhir try
            catch(Exception e){
                System.out.println("Koneksi Gagal " +e.getMessage());
            }
        } // Akhir Event
    }//GEN-LAST:event_txtKodeMataKuliahKeyPressed

    private void txtNIPKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNIPKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==10){
            try {
                Connection conn = Koneksi.getKoneksi();

                String sql="SELECT * FROM dosen WHERE nip=?";
                PreparedStatement st=conn.prepareStatement(sql);
                st.setString(1,txtNIP.getText());
                ResultSet rs= st.executeQuery();
                if( rs.next()){
                    String nama_dosen = rs.getString("nama_dosen");
                    txtNamaDosen.setText(nama_dosen);
                } else{
                    JOptionPane.showMessageDialog(this, "NIP Tidak  Ada","Informasi",JOptionPane.INFORMATION_MESSAGE);
                    txtNamaDosen.setText("");
                }
            } // akhir try
            catch(Exception e){
                System.out.println("Koneksi Gagal " +e.getMessage());
            }
        } // Akhir Event
    }//GEN-LAST:event_txtNIPKeyPressed

    private void txtNIMKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNIMKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==10){
            try {
                Connection conn = Koneksi.getKoneksi();

                String sql="SELECT * FROM mahasiswa WHERE nim=?";
                PreparedStatement st=conn.prepareStatement(sql);
                st.setString(1,txtNIM.getText());
                ResultSet rs= st.executeQuery();
                if( rs.next()){
                    String nama = rs.getString("nama");
                    String jurusan = rs.getString("jurusan");
                    String jk = rs.getString("jk");
                    String ta = rs.getString("ta");
                    txtNamaMahasiswa.setText(nama);
                    txtFakultas.setText(jurusan);
                    txtProdi.setText(jk);
                    txtKelas.setText(ta);
                } else{
                    JOptionPane.showMessageDialog(this, "NIM Tidak  Ada","Informasi",JOptionPane.INFORMATION_MESSAGE);
                    txtNamaMahasiswa.setText("");
                    txtFakultas.setText("");
                    txtProdi.setText("");
                    txtKelas.setText("");
                }
            } // akhir try
            catch(Exception e){
                System.out.println("Koneksi Gagal " +e.getMessage());
            }
        } // Akhir Event
    }//GEN-LAST:event_txtNIMKeyPressed

    private void bTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTambahActionPerformed
        // TODO add your handling code here:
        bTambah.setEnabled(false);
        txtKodeMataKuliah.setEnabled(true);
        txtNIM.setEnabled(true);
        txtNIP.setEnabled(true);
        
    }//GEN-LAST:event_bTambahActionPerformed

    private void txtNamaDosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaDosenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaDosenActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int idEdit = jTable3.getSelectedRow();

        String nim = (String) jTable3.getModel().getValueAt(idEdit, 0);
        String kode_mk = (String) jTable3.getModel().getValueAt(idEdit, 1);
        String semester = (String) jTable3.getModel().getValueAt(idEdit, 2);
        String nilai_tugas = (String) jTable3.getModel().getValueAt(idEdit, 3);
        String nilai_uts = (String) jTable3.getModel().getValueAt(idEdit, 4);        
        String nilai_uas = (String) jTable3.getModel().getValueAt(idEdit, 5);


        System.out.print(nim+",");
        System.out.print(kode_mk+",");
        System.out.print(semester+",");
        System.out.print(nilai_tugas+",");
        System.out.print(nilai_uts+",");
        System.out.print(nilai_uas+",");

        final String JDBC_DRIVER = "com.mysql.jdbc.Driver";
        final String DB_URL = "jdbc:mysql://localhost/dbakademik";

        //  Database credentials
        final String USER = "root";
        final String PASS = "";

        Connection conn = null;
        Statement stmt = null;
        try{
            //STEP 2: Register JDBC driver
            Class.forName("com.mysql.jdbc.Driver");

            //STEP 3: Open a connection
            System.out.println("Connecting to a selected database...");
            conn = DriverManager.getConnection(DB_URL, USER, PASS);
            System.out.println("Connected database successfully...");

            //STEP 4: Execute a query
            System.out.println("Inserting records into the table...");
            stmt = conn.createStatement();

            String sql = "UPDATE penilaian " +
            "SET `nim`='"+nim+"',`kode_mk`='"+kode_mk+"',`nilai_tugas`='"+nilai_tugas+"',`nilai_uts`='"+nilai_uts+"',`nilai_uas`="+nilai_uas+" "
            + "WHERE nim='"+nim+"'";
            System.out.println(sql);
            stmt.executeUpdate(sql);
            System.out.println("Inserted records into the table...");

            //tampilObat();

        }catch(SQLException se){
            //Handle errors for JDBC
            se.printStackTrace();
        }catch(Exception e){
            //Handle errors for Class.forName
            e.printStackTrace();
        }finally{
            //finally block used to close resources
            try{
                if(stmt!=null)
                conn.close();
            }catch(SQLException se){
            }// do nothing
            try{
                if(conn!=null)
                conn.close();
            }catch(SQLException se){
                se.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        String nim = txtNIM.getText();
        String kode_mk = txtKodeMataKuliah.getText();
        String semester = jTextField1.getText();
        String nilai_tugas = jTextField3.getText();
        String nilai_uts = jTextField4.getText();
        String nilai_uas = jTextField5.getText();
        
        
            JOptionPane.showMessageDialog(this, "Masih Ada Data yang Kosong","Informasi",JOptionPane.INFORMATION_MESSAGE);
        
        // JDBC driver name and database URL
        final String JDBC_DRIVER = "com.mysql.jdbc.Driver";
        final String DB_URL = "jdbc:mysql://localhost/dbakademik";
        
        //  Database credentials
        final String USER = "root";
        final String PASS = "";

        Connection conn = null;
        Statement stmt = null;
        try{
            //STEP 2: Register JDBC driver
            Class.forName("com.mysql.jdbc.Driver");

            //STEP 3: Open a connection
            System.out.println("Connecting to a selected database...");
            conn = DriverManager.getConnection(DB_URL, USER, PASS);
            System.out.println("Connected database successfully...");

            //STEP 4: Execute a query
            System.out.println("Inserting records into the table...");
            stmt = conn.createStatement();
            String sql = "INSERT INTO penilaian " +
            "VALUES ('"+nim+"','"+kode_mk+"','"+semester+"','"+nilai_tugas+"','"+nilai_uts+"','"+nilai_uas+"')";
            stmt.executeUpdate(sql);
            System.out.println("Inserted records into the table...");

            tampilPenilaian();

        }catch(SQLException se){
            //Handle errors for JDBC
            se.printStackTrace();
        }catch(Exception e){
            //Handle errors for Class.forName
            e.printStackTrace();
        }finally{
            //finally block used to close resources
            try{
                if(stmt!=null)
                conn.close();
            }catch(SQLException se){
            }// do nothing
            try{
                if(conn!=null)
                conn.close();
            }catch(SQLException se){
                se.printStackTrace();
            }//end finally try
        }//end try
            
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int idEdit = jTable3.getSelectedRow();

        String nim = (String) jTable3.getModel().getValueAt(idEdit, 0);

        final String JDBC_DRIVER = "com.mysql.jdbc.Driver";
        final String DB_URL = "jdbc:mysql://localhost/dbakademik";

        //  Database credentials
        final String USER = "root";
        final String PASS = "";

        Connection conn = null;
        Statement stmt = null;
        try{
            //STEP 2: Register JDBC driver
            Class.forName("com.mysql.jdbc.Driver");

            //STEP 3: Open a connection
            System.out.println("Connecting to a selected database...");
            conn = DriverManager.getConnection(DB_URL, USER, PASS);
            System.out.println("Connected database successfully...");

            //STEP 4: Execute a query
            System.out.println("Inserting records into the table...");
            stmt = conn.createStatement();

            String sql = "DELETE FROM penilaian WHERE nim='"+nim+"'";
            System.out.println(sql);
            stmt.executeUpdate(sql);
            System.out.println("Inserted records into the table...");

            tampilPenilaian();

        }catch(SQLException se){
            //Handle errors for JDBC
            se.printStackTrace();
        }catch(Exception e){
            //Handle errors for Class.forName
            e.printStackTrace();
        }finally{
            //finally block used to close resources
            try{
                if(stmt!=null)
                conn.close();
            }catch(SQLException se){
            }// do nothing
            try{
                if(conn!=null)
                conn.close();
            }catch(SQLException se){
                se.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        tampilPenilaian();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txtNIMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNIMActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtNIMActionPerformed

    private void txtKodeMataKuliahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKodeMataKuliahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKodeMataKuliahActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InputForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InputForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InputForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InputForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InputForm().setVisible(true);
            }
        });
        tampilPenilaian();
    }
    
    public static void tampilPenilaian(){
        final String JDBC_DRIVER = "com.mysql.jdbc.Driver";  
        final String DB_URL = "jdbc:mysql://localhost/dbakademik";

        //  Database credentials
        final String USER = "root";
        final String PASS = "";
   
        Connection conn = null;
        Statement stmt = null;
        try{
           //STEP 2: Register JDBC driver
           Class.forName("com.mysql.jdbc.Driver");

           //STEP 3: Open a connection
           System.out.println("Connecting to a selected database...");
           conn = DriverManager.getConnection(DB_URL, USER, PASS);
           System.out.println("Connected database successfully...");
                System.out.println("Creating statement...");
             stmt = conn.createStatement();

             String sql = "SELECT * FROM penilaian WHERE 1 LIMIT 0, 10";
             ResultSet rs = stmt.executeQuery(sql);
             //STEP 5: Extract data from result set
             int i=0;
        
             while(rs.next()){
                //Retrieve by column name
                String nim  = rs.getString("nim");
                String kode_mk = rs.getString("kode_mk");
                String semester = rs.getString("semester");
                String nilai_tugas = rs.getString("nilai_tugas");
                String nilai_uts = rs.getString("nilai_uts");
                String nilai_uas = rs.getString("nilai_uas");


            
                jTable3.getModel().setValueAt(nim, i, 0);
                jTable3.getModel().setValueAt(kode_mk, i, 1);
                jTable3.getModel().setValueAt(semester, i, 2);
                jTable3.getModel().setValueAt(nilai_tugas, i, 3);
                jTable3.getModel().setValueAt(nilai_uts, i, 4);
                jTable3.getModel().setValueAt(nilai_uas, i, 5);
                
                i++;
             }
             rs.close();
          }catch(SQLException se){
             //Handle errors for JDBC
             se.printStackTrace();
          }catch(Exception e){
             //Handle errors for Class.forName
             e.printStackTrace();
          }finally{
             //finally block used to close resources
             try{
                if(stmt!=null)
                   conn.close();
             }catch(SQLException se){
             }// do nothing
             try{
                if(conn!=null)
                   conn.close();
             }catch(SQLException se){
                se.printStackTrace();
             }//end finally try
          }//end try
          System.out.println("Goodbye!");
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bTambah;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane3;
    private static javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JLayeredPane layerDosen;
    private javax.swing.JLayeredPane layerMahasiswa;
    private javax.swing.JLayeredPane layerMataKuliah;
    private javax.swing.JLabel lblFakultas;
    private javax.swing.JLabel lblKelas;
    private javax.swing.JLabel lblKodeMataKuliah;
    private javax.swing.JLabel lblNIM;
    private javax.swing.JLabel lblNIP;
    private javax.swing.JLabel lblNamaDosen;
    private javax.swing.JLabel lblNamaMahasiswa;
    private javax.swing.JLabel lblNamaMataKuliah;
    private javax.swing.JLabel lblProdi;
    private javax.swing.JLabel lblSKS;
    private javax.swing.JPanel pDosen;
    private javax.swing.JPanel pMahasiswa;
    private javax.swing.JPanel pMataKuliah;
    private javax.swing.JTextField txtFakultas;
    private javax.swing.JTextField txtKelas;
    private javax.swing.JTextField txtKodeMataKuliah;
    private javax.swing.JTextField txtNIM;
    private javax.swing.JTextField txtNIP;
    private javax.swing.JTextField txtNamaDosen;
    private javax.swing.JTextField txtNamaMahasiswa;
    private javax.swing.JTextField txtNamaMataKuliah;
    private javax.swing.JTextField txtProdi;
    private javax.swing.JTextField txtSKS;
    // End of variables declaration//GEN-END:variables
}
